### ISSUE TITLE
Certification sp_io dependency

### ISSUE THREAD

**Issue by SHA888** [debionetwork/debio-node#32]
**Description**

When I tried to run ```cargo check -p node-template-runtime``` or ```cargo check -p debio-node``` it throws an error:
```
failed to select a version for `certifications`.
    ... required by package `node-template-runtime v3.0.0 (/home/user/debio/debio-node/runtime)`
    ... which is depended on by `debio-node v0.1.0 (/home/user/debio/debio-node/node)`
versions that meet the requirements `=0.1.0` are: 0.1.0

the package `node-template-runtime` depends on `certifications`, with features: `sp-io` but `certifications` does not have these features.


failed to select a version for `certifications` which could resolve this conflict
```

**Steps to Reproduce**

1. Go to root folder
2. Run ``cargo check -p node-template-runtime``` or ```cargo check -p debio-node```

**Expected vs. Actual Behavior**
Expected: check passes
Actual: Failed

**Environment**

- Operating system: Linux Ubuntu 20.04
- Template version/tag:
- Rust version :
  Default host: x86_64-unknown-linux-gnu
  rustup home:  /home/sha888/.rustup

  installed toolchains
  --------------------

  stable-x86_64-unknown-linux-gnu (default)
  nightly-x86_64-unknown-linux-gnu

  active toolchain
  ----------------

  stable-x86_64-unknown-linux-gnu (default)
  rustc 1.53.0 (53cb7b09b 2021-06-17)

@kevinjanada @agustinustheo Any idea what might I went wrong? Thanks

**Comment by SHA888** [comment]
Also it fails on ```orders``` package/workspace.
For all others package:
```
    certifications
    traits-certifications
    doctor-certifications
    traits-doctor-certifications
    doctors
    traits-user-profile
    electronic-medical-record
    traits-electronic-medical-record
    genetic-testing
    traits-genetic-testing
    traits-order
    hospital-certifications
    traits-hospital-certifications
    hospitals
    labs
    traits-services
    services
    user-profile
```
are passed.

**Comment by kevinjanada** [comment]
I think this has to do with how crate features are defined in Cargo.toml files.
If you go to `pallets/certifications/Cargo.toml` on line 39 there's `sp-io/std`. But sp-io is not included in the dependencies, rather it is included in dev-dependencies.
Usually only items in dependencies get included in the std list of the features section.

I changed `sp-io/std` to `sp-std/std` since `sp-std` is included in dependencies and ran `cargo check -p node-template-runtime` again.
The error disappeared but the same error is also found in `doctor-certifiactions` pallet. I suspect this error will also be found in other pallets.

Perhaps you would like to take on this task to fix the errors on the other pallets?

As for the reason of the error, i am still not sure. To be honest i still need to get a better understanding on how crate features work.

**Comment by SHA888** [comment]
@kevinjanada Sure, I'll work on it. Thank you for the guidance

**Comment by SHA888** [comment]
I've created a PR review (under other DnaSampleStatus PR)
https://github.com/debionetwork/debio-node/pull/37/commits/ab36d040bea092aa54862f120e8e8a404bdf401f

They have been fixed by moving the `sp_io` and `sp_core` from dev-dependencies to dependencies in pallets
